name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run tests (includes nbval to test the Jupyter Notebook and other test files)
      - name: Run tests
        run: |
          pytest --nbval notebooks/descriptive_stats.ipynb
          pytest tests/test_script.py tests/test_lib.py

      # Format code using black
      - name: Format code
        run: |
          black src/ tests/

      # Lint code using Ruff
      - name: Lint code
        run: |
          ruff src/ tests/

      # Run the main script to generate summary report and plot
      - name: Run script and generate report
        run: |
          python src/main.py

      # Configure Git user identity for commit
      - name: Configure Git user identity
        run: |
          git config --global user.email "zichunwang733@gmail.com"
          git config --global user.name "chun77"

      # Commit and push generated files if there are changes
      - name: Generate summary report and commit
        run: |
          git add output/summary_report.md output/total_medals_by_top_50_countries.png
          if ! git diff --cached --quiet; then
            git commit -m "Add summary report and data visualization"
            git push
          else
            echo "No changes to commit"
