name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Jupyter notebook and save output
        run: |
          jupyter nbconvert --to notebook --inplace --execute ../notebooks/descriptive_stats.ipynb

      - name: Lint with Ruff
        run: |
          ruff check src/ tests/

      - name: Format with Black
        run: |
          black src/ tests/

      - name: Commit executed notebook
        run: |
          git config --global user.email "zichunwang733@gmail.com"
          git config --global user.name "chun77"
          git add descriptive_stats.ipynb
          git commit -m "Add executed notebook with outputs"
          git push
        continue-on-error: true
